# Generated by Django 5.0.6 on 2024-07-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_recipes_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='steps',
            field=models.CharField(default='None', max_length=2000),
        ),
    ]
